SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE
FROM MEMBER_PROFILE A
LEFT JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(A.CNT)
        FROM (
            SELECT COUNT(MEMBER_ID) CNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) A
    )
)
ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT
;