-- 코드를 입력하세요
SELECT YEAR(s.SALES_DATE) YEAR, MONTH(s.SALES_DATE) MONTH, u.GENDER GENDER, COUNT(DISTINCT u.USER_ID) USERS
FROM USER_INFO u
LEFT JOIN ONLINE_SALE s ON u.USER_ID = s.USER_ID
WHERE u.GENDER IS NOT NULL AND s.online_sale_id IS NOT NULL
GROUP BY YEAR(s.SALES_DATE), MONTH(s.SALES_DATE), u.GENDER
ORDER BY YEAR, MONTH, GENDER;