-- 코드를 입력하세요
SELECT 
    YEAR(B.SALES_DATE) YEAR, MONTH(B.SALES_DATE) MONTH, 
    COUNT(DISTINCT B.USER_ID) PUCHASED_USERS, 
    ROUND(
        COUNT(DISTINCT B.USER_ID) / (
            SELECT COUNT(*)
            FROM USER_INFO
            WHERE YEAR(JOINED) = 2021
        )
    , 1) PUCHASED_RATIO
FROM USER_INFO A
RIGHT JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE YEAR(A.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;