-- 코드를 입력하세요
SELECT B.HISTORY_ID, ROUND(A.DAILY_FEE * B.DURATION * (100 - B.DISCOUNT_RATE)/100) FEE
FROM CAR_RENTAL_COMPANY_CAR A
LEFT JOIN (
    SELECT 
        HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 DURATION,
        (CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE LIKE "트럭" AND DURATION_TYPE LIKE "90%")
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE LIKE "트럭" AND DURATION_TYPE LIKE "30%")
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE LIKE "트럭" AND DURATION_TYPE LIKE "7%")
            ELSE 0
        END) DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) B ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE LIKE "트럭"
ORDER BY FEE DESC, B.HISTORY_ID DESC
;