-- 코드를 입력하세요
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(bs.SALES*b.PRICE) TOTAL_SALES -- 판매량 * 판매가
FROM AUTHOR a
INNER JOIN BOOK b ON a.AUTHOR_ID = b.AUTHOR_ID
INNER JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
WHERE YEAR(bs.SALES_DATE) = 2022 AND MONTH(bs.SALES_DATE) = 1
GROUP BY b.CATEGORY, a.AUTHOR_ID, a.AUTHOR_NAME
ORDER BY a.AUTHOR_ID, b.CATEGORY DESC
;