SELECT A.CAR_ID, A.CAR_TYPE, ROUND(30 * A.DAILY_FEE * (100 - B.DISCOUNT_RATE)/100) FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON A.CAR_TYPE = B.CAR_TYPE
WHERE B.DURATION_TYPE LIKE "30%"
AND A.CAR_ID NOT IN (
    SELECT D.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY D
    WHERE D.END_DATE >= '2022-11-01' AND D.START_DATE <= '2022-12-01'
)
AND A.CAR_TYPE IN ('세단', 'SUV')
GROUP BY A.CAR_ID
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC;